version: '2'
services:
  mi-mongo:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rootuser
      - MONGO_INITDB_ROOT_PASSWORD=rootpass 
    ports:
      - 27017:27017
    volumes:
      - mongodb-data:/data/db
    networks:
      - mi-red

  mongo-express:
    image: mongo-express
    restart: always
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=rootuser
      - ME_CONFIG_MONGODB_ADMINPASSWORD=rootpass
      - ME_CONFIG_MONGODB_SERVER=mi-mongo
    networks:
      - mi-red
    ports:
      - 8081:8081
    depends_on:
      - mi-mongo

volumes:
  mongodb-data:
    driver: local

networks:
   mi-red:
    driver: bridge
    
