version: '3.3'

services:
  db:
    image: mysql:debian
    restart: always
    environment:
      MYSQL_DATABASE: mi-sql
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
      MYSQL_ROOT_PASSWORD: rootpass
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app_network

  phpmyadmin:
    image: phpmyadmin:apache
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpass
    networks:
      - app_network

networks:
  app_network:

volumes:
  db_data:
    